dbt_ippon_training:
  target: dev
  outputs:
    dev:
      account: "{{env_var('DBT_ACCOUNT_NAME')}}"
      type: snowflake
      database: "{{env_var('DBT_DB_NAME')}}"
      role: "{{env_var('DBT_ROLE_NAME')}}"
      schema: "{{env_var('DBT_SCHEMA_NAME')}}"
      threads: 4
      user: "{{env_var('DBT_PRIVATE_USERNAME')}}"
      password: "{{env_var('DBT_ENV_SECRET_PASSWORD')}}"
      warehouse: "{{env_var('DBT_WH_NAME')}}"